[project]
name = "web-chat-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-socketio>=5.5.1",
    "mysql-connector-python>=9.3.0",
    "openai>=1.82.1",
    "requests>=2.32.3",
]
